import RainichKaluza

/-!
This file is intentionally not imported by the library root. Running it prints
the axiom dependencies of the current advertised theorem surface.
-/

#print axioms RainichKaluza.monicQuartic_fromFactorization
#print axioms RainichKaluza.protected_positive_root
#print axioms RainichKaluza.protected_negative_root
#print axioms RainichKaluza.kaluzaObstruction_fromFactorization
#print axioms RainichKaluza.reconstructedQSq_fromFactorization
#print axioms RainichKaluza.obstruction_zero_iff_reconstructed_constant
#print axioms RainichKaluza.kaluzaObstruction_perfectFluid
#print axioms RainichKaluza.kaluzaObstruction_algebraicFalsePositive
#print axioms RainichKaluza.algebraicFalsePositive_has_no_real_protected_pair
#print axioms RainichKaluza.reconstructedDiagonalA_solves
#print axioms RainichKaluza.reconstructedDiagonalB_solves
#print axioms RainichKaluza.reconstructedDiagonal_sum
#print axioms RainichKaluza.reconstructedDiagonal_product
#print axioms RainichKaluza.exists_real_rankOne_completion_iff
#print axioms RainichKaluza.exists_reconstructed_rankOne_completion_iff
#print axioms RainichKaluza.offDiagonal_eq_zero_of_nonresonant
#print axioms RainichKaluza.complementary_offDiagonal_is_resonant
#print axioms RainichKaluza.protectedDiagonal_eq_zero
#print axioms RainichKaluza.scalarMixedBlock_rankOne
#print axioms RainichKaluza.scalarMixedBlock_metric_selfAdjoint
#print axioms RainichKaluza.scalarMixedBlock_components_unique_up_to_sign
#print axioms RainichKaluza.exists_scalar_components_iff
#print axioms RainichKaluza.reconstructedBlock_has_scalar_factorization_iff
#print axioms RainichKaluza.solvesComplementaryBlock_iff
#print axioms RainichKaluza.exists_scalarComplementaryBlock_iff
#print axioms RainichKaluza.reconstructionEquation_of_decomposition
#print axioms RainichKaluza.reconstructionEquation_of_eq_add
