import RainichKaluza.GenericReconstruction
import Mathlib.Analysis.Real.Sqrt
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring

/-!
# Lorentzian scalar block

In a pseudo-orthonormal eigenbasis with metric signs `εᵢ ∈ {±1}`, a covector
component pair `(x,y)` produces the mixed rank-one tensor

`Vⁱⱼ = 1/2 vⁱ vⱼ`.

Consequently the diagonal and off-diagonal entries carry the row signature
sign. This file separates that Lorentzian factorization from the weaker claim
that a two-by-two matrix merely has rank one.
-/

namespace RainichKaluza

/-- A mixed two-by-two tensor block in the complementary eigenspace. -/
structure MixedBlock where
  aa : ℝ
  ab : ℝ
  ba : ℝ
  bb : ℝ

/-- A diagonal mixed-tensor entry generated by a scalar covector component. -/
noncomputable def scalarMixedDiagonal (epsilon x : ℝ) : ℝ :=
  epsilon * x ^ 2 / 2

/-- An off-diagonal mixed-tensor entry generated by scalar covector components.
The sign belongs to the raised (row) index. -/
noncomputable def scalarMixedOffDiagonal (epsilon x y : ℝ) : ℝ :=
  epsilon * x * y / 2

/-- The full mixed block generated by two scalar covector components. -/
noncomputable def scalarMixedBlockOfComponents
    (epsilonA epsilonB x y : ℝ) : MixedBlock where
  aa := scalarMixedDiagonal epsilonA x
  ab := scalarMixedOffDiagonal epsilonA x y
  ba := scalarMixedOffDiagonal epsilonB y x
  bb := scalarMixedDiagonal epsilonB y

/-- Component equations obtained by restricting the Sylvester reconstruction
equation to the complementary `a,b` eigenspace. The middle two equations retain
the eigenvalue-sum resonance explicitly. -/
def SolvesComplementaryBlock
    (a b qSq : ℝ) (block : MixedBlock) : Prop :=
  (2 * a - (a + b)) * block.aa = a ^ 2 - qSq ∧
  (a + b - (a + b)) * block.ab = 0 ∧
  (b + a - (a + b)) * block.ba = 0 ∧
  (2 * b - (a + b)) * block.bb = b ^ 2 - qSq

/-- The mixed two-by-two scalar block has zero determinant. -/
theorem scalarMixedBlock_rankOne
    (epsilonA epsilonB x y : ℝ) :
    scalarMixedDiagonal epsilonA x * scalarMixedDiagonal epsilonB y =
      scalarMixedOffDiagonal epsilonA x y *
        scalarMixedOffDiagonal epsilonB y x := by
  simp [scalarMixedDiagonal, scalarMixedOffDiagonal]
  ring

/-- Lowering the raised index makes the off-diagonal block symmetric. -/
theorem scalarMixedBlock_metric_selfAdjoint
    (epsilonA epsilonB x y : ℝ)
    (hepsilonA : epsilonA ^ 2 = 1)
    (hepsilonB : epsilonB ^ 2 = 1) :
    epsilonA * scalarMixedOffDiagonal epsilonA x y =
      epsilonB * scalarMixedOffDiagonal epsilonB y x := by
  calc
    epsilonA * scalarMixedOffDiagonal epsilonA x y =
        epsilonA ^ 2 * x * y / 2 := by
          simp [scalarMixedOffDiagonal]
          ring
    _ = x * y / 2 := by rw [hepsilonA]; ring
    _ = epsilonB ^ 2 * y * x / 2 := by rw [hepsilonB]; ring
    _ = epsilonB * scalarMixedOffDiagonal epsilonB y x := by
      simp [scalarMixedOffDiagonal]
      ring

/-- **Discrete uniqueness of scalar components.** If the first scalar
component is nonzero, two component pairs generate the same mixed block only
when they agree or differ by the simultaneous global sign. This is the local
`v ↦ -v` ambiguity expected when reconstructing a rank-one tensor. -/
theorem scalarMixedBlock_components_unique_up_to_sign
    (epsilonA epsilonB x y x' y' : ℝ)
    (hepsilonA : epsilonA ^ 2 = 1)
    (hx : x ≠ 0)
    (hblock :
      scalarMixedBlockOfComponents epsilonA epsilonB x y =
        scalarMixedBlockOfComponents epsilonA epsilonB x' y') :
    (x' = x ∧ y' = y) ∨ (x' = -x ∧ y' = -y) := by
  have hepsilonA_ne : epsilonA ≠ 0 := by
    intro hepsilonA_zero
    rw [hepsilonA_zero, zero_pow (by norm_num : 2 ≠ 0)] at hepsilonA
    norm_num at hepsilonA
  have haa := congrArg MixedBlock.aa hblock
  have hab := congrArg MixedBlock.ab hblock
  simp [scalarMixedBlockOfComponents, scalarMixedDiagonal] at haa
  simp [scalarMixedBlockOfComponents, scalarMixedOffDiagonal] at hab
  have hsq : x ^ 2 = x' ^ 2 := haa.resolve_right hepsilonA_ne
  rcases (sq_eq_sq_iff_eq_or_eq_neg).mp hsq with hsame | hopp
  · have hxx : x' = x := hsame.symm
    have hab' : (epsilonA * x) * y = (epsilonA * x) * y' := by
      rw [hxx] at hab
      linarith
    have hyy : y' = y :=
      (mul_left_cancel₀ (mul_ne_zero hepsilonA_ne hx) hab').symm
    exact Or.inl ⟨hxx, hyy⟩
  · have hxx : x' = -x := by linarith
    have hab' : (epsilonA * x) * y = (epsilonA * x) * (-y') := by
      rw [hxx] at hab
      linarith
    have hyy : y' = -y := by
      have : y = -y' :=
        mul_left_cancel₀ (mul_ne_zero hepsilonA_ne hx) hab'
      linarith
    exact Or.inr ⟨hxx, hyy⟩

/-- **Signature-aware factorization criterion.** Prescribed mixed diagonal
entries `u,v` come from real scalar covector components in signature directions
`epsilonA,epsilonB` exactly when their lowered diagonal values are nonnegative.
-/
theorem exists_scalar_components_iff
    (epsilonA epsilonB u v : ℝ)
    (hepsilonA : epsilonA ^ 2 = 1)
    (hepsilonB : epsilonB ^ 2 = 1) :
    (∃ x y : ℝ,
      u = scalarMixedDiagonal epsilonA x ∧
      v = scalarMixedDiagonal epsilonB y) ↔
      0 ≤ epsilonA * u ∧ 0 ≤ epsilonB * v := by
  constructor
  · rintro ⟨x, y, rfl, rfl⟩
    constructor
    · simp [scalarMixedDiagonal]
      nlinarith [sq_nonneg x]
    · simp [scalarMixedDiagonal]
      nlinarith [sq_nonneg y]
  · rintro ⟨hu, hv⟩
    let x := Real.sqrt (2 * epsilonA * u)
    let y := Real.sqrt (2 * epsilonB * v)
    have hxarg : 0 ≤ 2 * epsilonA * u := by linarith
    have hyarg : 0 ≤ 2 * epsilonB * v := by linarith
    have hx : x ^ 2 = 2 * epsilonA * u := by
      exact Real.sq_sqrt hxarg
    have hy : y ^ 2 = 2 * epsilonB * v := by
      exact Real.sq_sqrt hyarg
    refine ⟨x, y, ?_, ?_⟩
    · unfold scalarMixedDiagonal
      rw [hx]
      calc
        u = epsilonA ^ 2 * u := by rw [hepsilonA]; ring
        _ = epsilonA * (2 * epsilonA * u) / 2 := by ring
    · unfold scalarMixedDiagonal
      rw [hy]
      calc
        v = epsilonB ^ 2 * v := by rw [hepsilonB]; ring
        _ = epsilonB * (2 * epsilonB * v) / 2 := by ring

/-- The generic reconstructed diagonal block admits a real scalar factorization
exactly when both signature-adjusted forced diagonals are nonnegative. -/
theorem reconstructedBlock_has_scalar_factorization_iff
    (a b qSq epsilonA epsilonB : ℝ)
    (hepsilonA : epsilonA ^ 2 = 1)
    (hepsilonB : epsilonB ^ 2 = 1) :
    (∃ x y : ℝ,
      reconstructedDiagonalA a b qSq =
        scalarMixedDiagonal epsilonA x ∧
      reconstructedDiagonalB a b qSq =
        scalarMixedDiagonal epsilonB y) ↔
      0 ≤ epsilonA * reconstructedDiagonalA a b qSq ∧
      0 ≤ epsilonB * reconstructedDiagonalB a b qSq :=
  exists_scalar_components_iff epsilonA epsilonB
    (reconstructedDiagonalA a b qSq)
    (reconstructedDiagonalB a b qSq) hepsilonA hepsilonB

/-- **Classification of complementary Sylvester solutions.** Away from the
eigenvalue collision `a=b`, the component equation fixes exactly the two
diagonal entries and leaves the resonant off-diagonal pair free. -/
theorem solvesComplementaryBlock_iff
    (a b qSq : ℝ) (hab : a ≠ b) (block : MixedBlock) :
    SolvesComplementaryBlock a b qSq block ↔
      block.aa = reconstructedDiagonalA a b qSq ∧
      block.bb = reconstructedDiagonalB a b qSq := by
  constructor
  · rintro ⟨haa, _, _, hbb⟩
    have haa' : (a - b) * block.aa = a ^ 2 - qSq := by
      calc
        (a - b) * block.aa = (2 * a - (a + b)) * block.aa := by ring
        _ = a ^ 2 - qSq := haa
    have hforcedA :
        (a - b) * reconstructedDiagonalA a b qSq = a ^ 2 - qSq := by
      calc
        (a - b) * reconstructedDiagonalA a b qSq =
            (2 * a - (a + b)) * reconstructedDiagonalA a b qSq := by ring
        _ = a ^ 2 - qSq := reconstructedDiagonalA_solves a b qSq hab
    have hbb' : (b - a) * block.bb = b ^ 2 - qSq := by
      calc
        (b - a) * block.bb = (2 * b - (a + b)) * block.bb := by ring
        _ = b ^ 2 - qSq := hbb
    have hforcedB :
        (b - a) * reconstructedDiagonalB a b qSq = b ^ 2 - qSq := by
      calc
        (b - a) * reconstructedDiagonalB a b qSq =
            (2 * b - (a + b)) * reconstructedDiagonalB a b qSq := by ring
        _ = b ^ 2 - qSq := reconstructedDiagonalB_solves a b qSq hab
    constructor
    · exact mul_left_cancel₀ (sub_ne_zero.mpr hab) (haa'.trans hforcedA.symm)
    · exact mul_left_cancel₀ (sub_ne_zero.mpr (Ne.symm hab))
        (hbb'.trans hforcedB.symm)
  · rintro ⟨haa, hbb⟩
    refine ⟨?_, by ring, by ring, ?_⟩
    · rw [haa]
      exact reconstructedDiagonalA_solves a b qSq hab
    · rw [hbb]
      exact reconstructedDiagonalB_solves a b qSq hab

/-- **Pointwise generic scalar-block existence theorem.** A complementary
Sylvester solution generated by a real Lorentzian scalar covector exists
exactly under the two signature-adjusted diagonal inequalities. -/
theorem exists_scalarComplementaryBlock_iff
    (a b qSq epsilonA epsilonB : ℝ)
    (hab : a ≠ b)
    (hepsilonA : epsilonA ^ 2 = 1)
    (hepsilonB : epsilonB ^ 2 = 1) :
    (∃ x y : ℝ,
      SolvesComplementaryBlock a b qSq
        (scalarMixedBlockOfComponents epsilonA epsilonB x y)) ↔
      0 ≤ epsilonA * reconstructedDiagonalA a b qSq ∧
      0 ≤ epsilonB * reconstructedDiagonalB a b qSq := by
  constructor
  · rintro ⟨x, y, hsolves⟩
    have hdiag :=
      (solvesComplementaryBlock_iff a b qSq hab
        (scalarMixedBlockOfComponents epsilonA epsilonB x y)).mp hsolves
    apply (exists_scalar_components_iff epsilonA epsilonB
      (reconstructedDiagonalA a b qSq)
      (reconstructedDiagonalB a b qSq) hepsilonA hepsilonB).mp
    refine ⟨x, y, ?_, ?_⟩
    · simpa [scalarMixedBlockOfComponents] using hdiag.1.symm
    · simpa [scalarMixedBlockOfComponents] using hdiag.2.symm
  · intro hsign
    obtain ⟨x, y, hx, hy⟩ :=
      (exists_scalar_components_iff epsilonA epsilonB
        (reconstructedDiagonalA a b qSq)
        (reconstructedDiagonalB a b qSq) hepsilonA hepsilonB).mpr hsign
    refine ⟨x, y, (solvesComplementaryBlock_iff a b qSq hab
      (scalarMixedBlockOfComponents epsilonA epsilonB x y)).mpr ?_⟩
    constructor
    · simpa [scalarMixedBlockOfComponents] using hx.symm
    · simpa [scalarMixedBlockOfComponents] using hy.symm

/-- **Mixed-signature comparison audit.** The unsigned symmetric-completion
test and the Lorentzian scalar-factorization test are incomparable in general.

The first conjunct is the review counterexample: for `a=5`, `b=-5`, and
`qSq=5`, the forced diagonals are `2,-2`. Signature `(+,−)` admits a scalar
factorization although their product is negative. The second conjunct gives
the reverse failure: for `a=2`, `b=1`, and `qSq=2`, the forced diagonals have
nonnegative product, but signature `(−,+)` rejects them. -/
theorem reconstructed_signature_unsigned_tests_incomparable :
    ((0 ≤ (1 : ℝ) * reconstructedDiagonalA 5 (-5) 5 ∧
        0 ≤ (-1 : ℝ) * reconstructedDiagonalB 5 (-5) 5) ∧
      ¬ 0 ≤ reconstructedDiagonalA 5 (-5) 5 *
        reconstructedDiagonalB 5 (-5) 5) ∧
    ((0 ≤ reconstructedDiagonalA 2 1 2 *
        reconstructedDiagonalB 2 1 2) ∧
      ¬ (0 ≤ (-1 : ℝ) * reconstructedDiagonalA 2 1 2 ∧
        0 ≤ (1 : ℝ) * reconstructedDiagonalB 2 1 2)) := by
  norm_num [reconstructedDiagonalA, reconstructedDiagonalB]

end RainichKaluza
